### ISSUE TITLE
Replace file system data store with SQLite database

### ISSUE THREAD

**Issue by k0qed** [ARSFI/paclink-open-source#4]
Need to remove the existing file based data storage system and replace with SQLite database and appropriate tables. Some initial work has been done on this - settings/ini file has been replaced with the property table and associated classes.

[DB Browser (SQLite)](https://sqlitebrowser.org/) is a nice tool for managing the database.

**Comment by tmiw** [comment]
I have some updates to move the RMS channel list to SQLite. However, WinlinkWebServices seems to return an empty list from the server, so nothing gets added to the database. Does that particular request work properly for you or anyone else?

**Comment by k0qed** [comment]
The test CMS doesn't keep up to date with easily reproduced (in case of failure) data. I have a script I'll run to populate the database fully. It does get overwritten each day, though. So, just ping me anytime you need channel data for testing. I'll kick it off now - It should be there is 10-15 minutes.

**Comment by tmiw** [comment]
Thanks! I was able to confirm that it's working with no issues. 

BTW, I added [commit/rollback functionality for the channel list](https://github.com/ARSFI/paclink-open-source/blob/2c179826ab16a8ff422c79c21920514fba424fb9/Paclink.Data/Channel.cs#L19) but it might be better as something shared by the SQLiteDatabase class. Other than that, I made some general changes to the latter to keep one connection open instead of opening/closing it for every query (!) as the channel list population took forever otherwise.

**Comment by tmiw** [comment]
@k0qed, just pushed several commits that convert the various folders used in the original code for message handling to SQLite storage. There are some optimizations that can likely be done but quick testing seems to indicate that both send and receive work. 

Anyway, .NET File and Directory are still used in a fair number of places (mainly a lot of the TNC configuration stuff) and I'm not sure that can be 100% removed (e.g. for AGWPE).

**Comment by tmiw** [comment]
As we've been using SQLite for a bit, I'm closing this issue for now.
